### ISSUE TITLE
XML comments in syntax definition files are not parsed correctly

### ISSUE THREAD

**Issue by beNative** [t-edson/SynFacilSyn#10]
The parser returns an error on sections that were commented with standard XML comment tags `<!--` and `-->`

**Comment by t-edson** [comment]
This is not a problem of SynFacilSyn itself. It seems to be a problem of XMLRead unit. I will do some tests.

**Comment by t-edson** [comment]
It's fixed (XMLRead was OK). 
It will appear in the next version (0.9.5).
