### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by beNative** [t-edson/SynFacilSyn#11]
I'm trying to making a foldable highlighter for 'INI' files which allows to fold each section. I did not find a way to do it so far (or am I missing something here?).

A nice feature would be if sections and blocks can have references in their parameter values to user defined tokens like shown in the example below:

``` XML
<?xml version="1.0"?>
<Language Name="Settings file" Ext="ini properties settings">
   <Attribute Name="SectionName" Style="bu"/>
   <Comment Start=";"/>
   <Token Attribute="SectionName" Start="[" End="]"/>
   <Section Name="INISection" Start="$SectionName$" Folding="True"/>
</Language>             
```

In this simple example I'm using `$SectionName$` to denote the reference.

Is there a way to make INI section folding work in the current version? If I declare the folding section like:

``` XML
   <Section Name="INISection" Start="[" Folding="True"/>
```

it will not fold probably because the starting delimiter was also used in the 'SectionName' definition.

rgds,
Tim

**Comment by t-edson** [comment]
I will analyze the best syntax for implementing this feature. I have been conscious of this when I was thinking on implementing a HTML/XML highlighter.

By the moment you can do:

``` XML
<?xml version="1.0"?>
<Language Name="Settings file" Ext="ini properties settings">
   <Attribute Name="SectionName" Style="bu"/>
   <Comment Start=";"/>
   <Token Attribute="SectionName" Start="[" End="]"/>
   <Section Name="INISection" Start="[" Folding="True"/>
</Language>             
```

This works on the version 0.9.5b (currently published). 

Note:  The 0.9.5b is something like beta version. It could change (including the documentation) until the final release 0.9.5.

**Comment by t-edson** [comment]
I would recommend to add this line to your  highlighter:

``` XML
   <Token Attribute="Number" Start="="/>
```

In order to have a better appearance and for protect from the possible char "[" after the "=" char.

**Comment by beNative** [comment]
Hi,
With the new  0.9.5b it works fine, thank you! I also noticed that you translated the error messages which is great!
rgds,
Tim
