### ISSUE TITLE
Raise exceptions for parsing errors

### ISSUE THREAD

**Issue by beNative** [t-edson/SynFacilSyn#12]
When parsing errors occur these are shown by the highlighter component itself:
`ShowMessage(Err)`
By replacing them with raising exceptions (preferably custom exception descendants for each type of error) you will provide the application options to handle these exceptions.

rgds,
Tim

**Comment by t-edson** [comment]
I think It's a good idea, but it needs to be analyzed more, because it could be a considerable change in the mode of working with SynFacilSyn.
By  the way, the only point where it's used ShowMessage(), is in LoadFromFile().

**Comment by t-edson** [comment]
I will make some tests using exceptions for the errors. This is going to appear on the version 1.0b, that have much more routines for checking errors.

**Comment by t-edson** [comment]
Version 1.0b, only raise exceptions for errors.
