### ISSUE TITLE
tmLang files?

### ISSUE THREAD

**Issue by Alexey-T** [t-edson/SynFacilSyn#14]
Did u see st3 files.  do u think is possible to support?
https://github.com/Benvie/JavaScriptNext.tmLanguage
https://github.com/colinta/ApacheConf.tmLanguage

**Comment by Alexey-T** [comment]
I mean .tmLanguage.

**Comment by t-edson** [comment]
Sorry. I don't understand well.
Do you mean to highlight a *.tmLanguage file? It's just an XMl.
Do you mean to highlight a *.st3 file?
Do you mean to use a format similar to a *.tmLanguage file, like the file for to define the syntax of SynFacilSyn?

**Comment by Alexey-T** [comment]
3rd-->>make variant of code to support tmLang files. So i don';t need xml files, i use tmLang files and your code (it may be descendant of SynFacil or new component)

**Comment by t-edson** [comment]
I don't know the "tmLanguage" format and I'm not thinking on to develop some other format for the syntax file, by now. There is some other priorities. 
But it is possible to override the method LoadFromFile(), for to support other format. There is some "low level" functions for to define the syntax in SynFacilSyn.

**Comment by Alexey-T** [comment]
not good but I understand. tmLanguage files are just good
