### ISSUE TITLE
Doc

### ISSUE THREAD

**Issue by Alexey-T** [t-edson/SynFacilSyn#15]
a.Better odf (or rtf, but not good) format. b.Why not make EN text, one write, and all done. 90% don't read SP.

**Comment by t-edson** [comment]
It was originally on *.pdf format. I'm using an editable format, precisely for to make easy the translation. 
I use spanish, because it's my native language. It's more difficult for me to write a documentation in English. There was someone who started a translation. Let me see.

**Comment by Alexey-T** [comment]
ok Let hope he will make EN trans.

**Comment by t-edson** [comment]
There is a translation, but it need to be improved. It will appear soon, for the version 0.9.3. For the next versions, will be appearing progressively.

**Comment by t-edson** [comment]
First translation appeared in version 0.9.3. It need to be improved yet.
