### ISSUE TITLE
tmLang files

### ISSUE THREAD

**Issue by Alexey-T** [t-edson/SynFacilSyn#17]
Hello. I do ATSynedit and want to support tmLanguage files. Many many files exist: Python, C++, Pas, Go etc. More than 150. or 250.

Can u help with tmLang +ATSynedit integration? I improve synedit, you make tmLang support (unit which uses synedit)
It's XML

**Comment by beNative** [comment]
Hi Alexey,

I was not aware of tmLang, and after a small look I'm impressed by the clean and clear syntax. 

So Tito, I think this is a great idea and will make your highlighter work with many syntax descriptions that are already available to a wider public.

**Comment by t-edson** [comment]
I don't know tmLanguage, but looking at the web, seems interesting. There is good documentation for that. It has a lot of features, not all supported for SynFacilSyn, because SynFacilSyn is focused on speed, instead of flexibility.

I would like to know how ATSynedit works first, in order to know how easy would be the integration of a highlighter or parser. I have problems understanding code of another programmer if it's not well documented.

**Comment by Alexey-T** [comment]
Of coz; i ll tell how synedit works. Each detail. Im interested in tmLang; and don't know Laz regex code support. 
Now syned has this: method DoCalsHilite which gets 'var parameter' Parts. Parts is array of record, record is

```
TATLinePart = record
Offset, Len: integer;
Color, ColorBG: TColor;
Styles: TFontStyles;
end;
```

offset= offset 0-based from start of line (synedit has collection if lines) 
len=length of part (inside line)
styles= [fsBold, fsItalic]... etc

I need to do event
    OnCalcLineHilite
which gets `var Parts` and fills it. Event with line number.

**Comment by Alexey-T** [comment]
I added OnCalcLineHilite, as draft (it will disable selection hilite if set, it's to fix, later I do it)..

**Comment by t-edson** [comment]
I note that you refer to "synedit", "syned", "ATSynedit", and I'm not sure what are refreing to. Do you have a version of ATSynedit for to check th editor?

**Comment by t-edson** [comment]
I noted that you refer to "synedit", "syned", or "ATSynedit", and I'm not sure what are refering to.
I'm bad on guessing words. Please be specific, for avoid misunderstanding. My english level is not so good.
I'm supposing (and I don't like to supouse) that there is not documentation for ATSynedit. Is n't it? 
Do you have a version of ATSynedit for to start checking?

**Comment by Alexey-T** [comment]
Hm, sorry: 'synedit', 'syned" all mean "ATSynEdit", it's at my github- see my profile. I don't use Laz SynEdit atall...

-there is not documentation for ATSynedit.
no such. Pls ask me (if want)

Pls see  github- download atsynedit, run `app\demo_editor\*.lpi` project

**Comment by Alexey-T** [comment]
For a start: added "Test-Hilite w in color" menuitem in `app\demo_editor`

![synt](https://cloud.githubusercontent.com/assets/4154978/7899659/2e2f2622-0735-11e5-9f68-c51a79ac3a4e.png)

**Comment by t-edson** [comment]
What is the state of ATSynEdit? Is it functional? I see it's very complete.
I see you use UnicodeString instead of UTF-8. Can I know why? It needs more memory for to work, and probably the process would be slower in some cases.

**Comment by t-edson** [comment]
You mentioned DoCalsHilite method. I don't see this method. 
According what I'm understanding: ATSynEdit implements Highlighting, calling repeatedly to the event OnCalcLineHilite(), and expect the properties of parameter "AParts", are filled there. I'm OK?

**Comment by Alexey-T** [comment]
...state of ATSynEdit? Is it functional? I see it's very complete.
It is very complete. except it doesnot have syntax hilite 

..I see you use UnicodeString instead of UTF-8.
reason: to easy find each CHAR by index. i just use Str[Index]. and get Unicodechar...

**Comment by Alexey-T** [comment]
..You mentioned DoCalsHilite method
In IDE press Alt-G (after opened PAS file): type in input "Docalc", see it? 
..am I right?
yes, OnCalcLineHilite

**Comment by Alexey-T** [comment]
`OnCalcHilite` is renamed,
added paramater (for wrap mode off)

    procedure TfmMain.EditCalcLine(Sender: TObject; var AParts: TATLineParts;
    const AWrapItem: TATSynWrapItem; ACharIndexFrom: integer);

how to use it? Pls see demo_editor, example, or ask..

**Comment by Alexey-T** [comment]
Hi; what do you think. Is it doable work.

**Comment by t-edson** [comment]
It's a lot of work. It would take some time.

**Comment by Alexey-T** [comment]
Ah ok; yes, I 'll wait for it

**Comment by Alexey-T** [comment]
Hi @magorium : maybe you interested in this task?

**Comment by t-edson** [comment]
Alexey, I think you should do a User Manual or something like this. In this way, it will be easier to make any development on your editor.

**Comment by Alexey-T** [comment]
I agree; later I may do it, now is active dev and it's bad to do, during active dev

**Comment by Alexey-T** [comment]
A demo , other engine http://uvviewsoft.com/bb/demo_adapter_econtrol.rar (just see - it works ok)

**Comment by t-edson** [comment]
A demo of what?
An engine of what?

**Comment by t-edson** [comment]
Alexey, I thing your editor is great, but in order to be motivated for to do some work on it, I need to use it, an for to use it, I need some documentation.

**Comment by Alexey-T** [comment]
hm; what part  you need? About OnCalc**** event. Or? about internal thing?

**Comment by Alexey-T** [comment]
Tell pls, what part to document.What for you: how to load file/ how to color lines (OnCalc event)/ how to......?

**Comment by t-edson** [comment]
Basically, there are two kinds of documents: 
1) For the user (user manual, operation manual, instalation guide, quick start)
2) For developers (technical documentation, programmers guide, ...)

For to use, it's important to have a User Manual. It must answer the following question:
- What is ATSynEdit? It'a a unit, library, component, a potato, an alien, ...?
- Whath it's not? What features it have? What limitations have?
- Similitude and difference from other components (like SynEdit)?
- How can I use it, in my programs? Does it need to be installed? Download sources?
- What parts does't it have?
- Wich are the their methods and properties?
- What is a basic code for to use ATSynEdit?
- How does it manage the coordinates? How does it show the information on screen?
- How to manage the cursor, the selection?
- How to modify the contents? lines, words, pargaraphs, pages, 
- Does it have search/replece? Highlighting?
  ...

**Comment by Alexey-T** [comment]
I see; well, no much time to do doc like it , now, so maybe later, ... not now. It\'s work to do doc about properties, proc's...

**Comment by Alexey-T** [comment]
I started doc http://wiki.freepascal.org/ATSynEdit -wait pls. N days. Will edit

**Comment by Alexey-T** [comment]
Done at beginning state. See wiki. Is it ok doc?

**Comment by t-edson** [comment]
Good. It can be improved, but it's OK, for the begin.
I see you say it has "adapters" for highlighting. Can you explain how it works?
And, if you have adpaters, why you need Highlighter?

**Comment by Alexey-T** [comment]
Thank.:) sure, I must write more if you ask more. U asked about adapters.It's object:     

```
atsynedit1.AdapterHilite:= MyAdapter
```

**Comment by Alexey-T** [comment]
added info at and (wiki page).

**Comment by t-edson** [comment]
Good. There is useful information in the wiki page. But I don't have an answer for the question: If you have adpaters, why you need Highlighter?
I saw you mention "atsynedit_adapters.pas". Where I can find this?
Do you have a sample using adapters?

**Comment by Alexey-T** [comment]
--If you have adpaters, why you need Highlighter?
Because i have adapter for econtrol. NOT for tmLang files. (I want adapter for tmLang files)

-Where I can find this?
In folder atsynedit. "download zip" at github

-Sample
 I have. See folder "app\demo_adapter_econtrol"

**Comment by Alexey-T** [comment]
Hi. Do u see demo (mentioned)?

**Comment by t-edson** [comment]
Yes, (I guess you refers to the  "app\demo_adapter_econtrol"), but it took me more time than expected. It seems to need some re-arrange on the architecture: 
- ATSynEdit requires ECOntrol.
- ECOntrol requires ATSynEdit.

**Comment by Alexey-T** [comment]
Yes i mean this, that demo for econ engine. You did see it and it should work. 

> seems to need some re-arrange on the architecture:
>    ATSynEdit requires ECOntrol.
>     ECOntrol requires ATSynEdit.

Rearrage is not needed, imo, why it needed.You see that it separate parts.

**Comment by Alexey-T** [comment]
I see how to make rearrange. maybe needed indeed. maybe need to comnine packg of econ and pack of control.

**Comment by Alexey-T** [comment]
hi. IMO no good to  make 1 packge econ+atsynedit, because econ must be in new place, it's code from not me and if Author wants to disable code, I want that he disables only 1 repo in github. i don't want block of all code with econ.

btw good, you asked GREAT questions and I wrote good wiki text. you may ask more. maybe i may write more.

**Comment by t-edson** [comment]
By the moment I'm working on an Android project, so have no time for to check ATSynEdit. I have a good aplication for your editor, but it will have to wait.
