### ISSUE TITLE
Facil for atSynEdit

### ISSUE THREAD

**Issue by Alexey-T** [t-edson/SynFacilSyn#18]
Feel free to ask more:if wiki misses txt, I write more or tell here...

**Comment by Alexey-T** [comment]
name may be "AdapterFacil" (like AdapterEControl)

**Comment by t-edson** [comment]
OK, it could be. I don't understand yet, how one adapter works.

**Comment by t-edson** [comment]
Now I'm updating the SynFacilSyn with some patchs and documentation, before to take the AtSynEdit version.

**Comment by Alexey-T** [comment]
adapter: don't do adapter. First do OnCalcHilite event.
If u ll do it--I ll help to make adapter

**Comment by t-edson** [comment]
I've checking the OnCalcHilite event on the \app\demo_editor. And can see that the key for highlighting, is to fill the AParts[] table with information about the tokens. The questions are:
1. Why you use  copy in Str:= Copy(ed.Strings.Lines[ALineIndex], ACharIndex, ALineLen) ?  Wouldn't be the same to do Str:= ed.Strings.Lines[ALineIndex]?
2. How do you implement highlighting for multi-line tokens like Comments? I only see a process "by line" without any reference to previous line.

**Comment by t-edson** [comment]
I think the information on the Wiki for highlighting must be clarified:

 == How to highlight syntax?  ==
Ther are two ways:
 === Using Adpter === 
...
 === Using the event OnCalcHilite  === 
...

**Comment by Alexey-T** [comment]
hi..
--The questions are:1. Why you use copy in Str:= Copy(ed.Strings.
Becaus Line can be 300 chars, and you need to get only ~~80 from it (wordwrap On)

--How do you implement highlighting for multi-line tokens 
As always for all lines. OnCalcHilite must work for all lines. if comment is 3 lines, OnCalchilite must give hilite for each of 3 lines

**Comment by Alexey-T** [comment]
information on the Wiki changed: thankx..

**Comment by Alexey-T** [comment]
Logic of OnCalchilite isnot simple. then.

**Comment by t-edson** [comment]
Good. But on multiline tokens, it's needed to know the state of the previous lines, for to work. One way would be to create an special structure for to save the state of every line. But I'm not sure it's the best way. Questions: 
1. Is there some way for to save adiitonal data for each line in ATSynEdit, like it's done in SynEdit?
2. How is the order in wich OnCalchilite() is called in a common edition task? I guess it's not always sequencial.

**Comment by Alexey-T** [comment]
- to create an special structure for to save the state
  yes, this struc is here in EControl, good to make it.It's ok that no more data saved.

Q1.: what data? TATStrings cannot have more data
Q2. from top line to bottom
skipped fully folded lines

**Comment by t-edson** [comment]
So I need to create my own structure for to save the state of the edit. I don't know how EControl works.

I wanted to include this data (state of the scanner for to highlight) on ATSynEdit, like SynEdit do, using the Object part of TSTrings.

"from top line to bottom"  I don't think so. I don't think that for every key pressed, all the text is scanned.

**Comment by Alexey-T** [comment]
U have file 200 lines. top scroll pos is 10, height 30 lines. 
u get indexes from 10 to 10+30..31

**Comment by Alexey-T** [comment]
--own structure for to save the state
Yes (don't see EControl- no need)

**Comment by t-edson** [comment]
Let me know if I understand: 
"For every time you press a key (no control key), ATSynEdit call OnCalchilite, for every visible line on the editor".

**Comment by Alexey-T** [comment]
Yes

**Comment by t-edson** [comment]
OK. A simple, an efective way to refresh.
Questions:
Why you make this verification:    if npart>High(AParts) then exit; ? 
Is the size of AParts limited? How many  "parts" can a I use?

**Comment by Alexey-T** [comment]
yep: limited; it is array! High(var) gets last index. Low()=0

**Comment by t-edson** [comment]
I know it's an array. I will change the question: In which situations I would have  npart>High(AParts)?

**Comment by Alexey-T** [comment]
in case I set loo small AParts len in my code. and editor line has many tokens.

**Comment by t-edson** [comment]
There is a first test of using SynFacilSyn here: 
https://github.com/t-edson/SynFacilSyn/tree/1.11/_demoSynFacilonATSynEdit
Like it's expected, It cann't process mutil-line tokens, because have non information of previous lines.
There is a dependency of the packet SynEdit.

**Comment by Alexey-T** [comment]
good. WIll test!

**Comment by Alexey-T** [comment]
good:keywords, comments ok hilited. :)
not others. My notes. 
- fix case of ProjPaths: Linux needs ok case
- function GetTokenKind: integer; override;  
  bad. Pointer 64bit. function 32bit. I see bad demo. 

need/ changed to

```
function GetTokenKind: PtrInt; reintroduce;    
```

**Comment by Alexey-T** [comment]
btw. EControl has all parse-ressults in memory. adapter calls it to get tokens multiline. U need to save results. And call em later..

**Comment by t-edson** [comment]
The demo is only a simple test. I will check the case of the paths, but I work on windows.

**Comment by t-edson** [comment]
GetTokenKind is a virtual method defined on the Base class. Using casting for to obtain th attribute is not the best way. I will consider to include a special function for to do it.

**Comment by Alexey-T** [comment]
yes, not best way. Gettokenkind not good. It is 32bit , I have amd64+Linux

**Comment by Alexey-T** [comment]
==special function for to do it.= Ok english "function to do it", no "for"

**Comment by t-edson** [comment]
Thank for the english correction. 
I was thinking, It would be better to have a space into ATSynEdit, for to storage the highlighting information. Have an external structure could be slower.

**Comment by Alexey-T** [comment]
"for to storage" again. (Wrong lang.) I don't get an idea. what storage..

**Comment by t-edson** [comment]
You know highlighter needs to have information of the state of previous line to right proccess the multiline tokens. This needs to have some structure (like an array) to save the state of every line. And I said ATSynEdit would have this structure.

**Comment by t-edson** [comment]
Having an external structure would make necessary to synchronize the size, every time the editor adds or removes lines. This is totally possible, but could be slower than have the storage internally in ATSynEdit.

**Comment by Alexey-T** [comment]
hm. atSynEdit also needs to remake structure on each change. And sync its size. no? it ll be same slower. Why i dont like idea? because much work for me. And u didn't say **what struct**\- Pointer for each line?

 i try to have small ATStrings. some users tell Cudatext gets 300Mb on big 10M file. Reason: many items in TATStrings

**Comment by t-edson** [comment]
300Mb for a 10M file? You really have a design problem. That's not efficient. 
Maybe you need to redesign.

**Comment by t-edson** [comment]
For highlighting, it's only necessary a pointer for each line.
Do you maintain an array (TATLineParts) for each line?
Using an array of static data for highlighting, is bad for memory.

**Comment by Alexey-T** [comment]
200M for 10M file maybe or 150M. I have record: see

```
TATStringItem = class
public
ItemString: atString;
ItemEnd: TATLineEnds;
ItemState: TATLineState;
ItemSeparator: TATLineSeparator;
ItemHidden: array[0..cMaxStringsClients-1] of smallint;
  //0: line visible,
  //-1: line hidden,
  //>0: line hidden from this char-pos
ItemBm: byte;
ItemBmColor: TColor;
```

**Comment by Alexey-T** [comment]
no I don't save TATLineParts..

**Comment by Alexey-T** [comment]
Do u want to make ok project, react to onchange, have XML's? i can make Adapter then. after u make code more full.

**Comment by t-edson** [comment]
Sorry. I don't understand what you say. I said I prefer ATSynEdit have an internal storage for highlighters.

**Comment by Alexey-T** [comment]
Why i donot want Pointer for each ATStrings line: it is 4 byte per line, 100000lines- 400K memory. 400K memory which not needed for almost all apps.
can you make your 'storage'?

**Comment by t-edson** [comment]
It will be probably slower, but it's possible. I need you to give me a detail of events to catch, in order to have a synchronized list with the size of the total editor lines.

**Comment by Alexey-T** [comment]
Okey:event is procedure 

```
TATAdapterHilite = class(TComponent)
public
  procedure OnEditorChange(Sender: TObject); virtual;
```

can you make adapter from OnCalcHilite? if yes, add to adapter this procedure

```
procedure OnEditorChange(Sender: TObject); override;
```

if no, I make adapter

**Comment by Alexey-T** [comment]
I can make adapter if u want

**Comment by t-edson** [comment]
I guess you are saying: "No. There is not events defined to capture changes on the editor. You need to use adapters for that."
This confused me.
"can you make adapter from OnCalcHilite?" 
I don't know exactly, how an adapter works. Do you have an basic sample of that?
What is the relation between adapters and OnCalcHilite?

**Comment by Alexey-T** [comment]
hm, wait a patch from me. i try making adapter

**Comment by bak20** [comment]
get my patch.Github req sent-ok?

**Comment by t-edson** [comment]
Accepted, but the directories was reordered.
I'm still waiting the responses to my questions:
1.  "No. There is not events defined to capture changes on the editor. You need to use adapters for that.". Is it OK?
2. What is the relation between adapters and OnCalcHilite?

**Comment by ghost** [comment]
responces
1.U can use both adapter and nonadapter. In adapter use procedure-i added 'showmessage'.
in non adapter use OnChange(OnChanged?)
1b.Cannot detect which lines changed
2.ATsynedit first calls Adapter if it assigned, then calls OnCalcHilite if assigned

**Comment by t-edson** [comment]
I see you have the type TATLineParts as a fixed Array, until 1000 elements. How many instances of TATLineParts do you have normally in ATSynEdit?

**Comment by ghost** [comment]
IMO, one instance if i correct

**Comment by t-edson** [comment]
IMHO, that array is information of the highlighter too, it must not be stored at the editor. It seems to me your design doesn't separate well the function of the highlighter and the editor.

**Comment by ghost** [comment]
I dont say it is stored. It is calced, then ed painted, then array deleted (array here only when needed)

**Comment by t-edson** [comment]
How do I know the index of the first line of TATSynEdit.Strings, that is visible on the screen?  And the the last line?

**Comment by t-edson** [comment]
Is it possible to know the first and the last line modified, after an operation like "Paste text" or a multi-line edition?

**Comment by Alexey-T** [comment]
index of the first line: prop LineTop, visible at btm: LineBottom. NN lines may be hidden in range (folded)

**Comment by Alexey-T** [comment]
ATStrings- property ListUpdates: TList, has indexes of lines chged. Maybe list clears before u get OnChange? need check..

**Comment by t-edson** [comment]
"ed.Strings.ListUpdates" doesn't give the lines modified. It's always empty.

**Comment by ghost** [comment]
so it cleared beffore OnChange. I don't have other

**Comment by t-edson** [comment]
I need to know the index of the first line modified. Ideas?
The array ed.Strings.lines[] is zero based index?

**Comment by ghost** [comment]
yep. Strings has event OnLog. 
forgot.

all indexes 0-base.

**Comment by t-edson** [comment]
ed.LineBottom is zero based index?

**Comment by ghost** [comment]
all 0-based.

**Comment by t-edson** [comment]
What information gives OnLog?

**Comment by ghost** [comment]
ALine is index of Strings/ ALen is len of text added, if <0: text deleted

**Comment by t-edson** [comment]
No all changes are Lines added/deleted. I need to know the index of the first line modified

**Comment by ghost** [comment]
u may get it in OnLog. Try see log when u change

**Comment by ghost** [comment]
for paste and text change too.

**Comment by t-edson** [comment]
Why "ed.LineBottom" give 0, the first time OnEditorChange() is called?
How do I know, when "ed.LineBottom", change?

**Comment by ghost** [comment]
hm, if it is 0,then take it as Strings.Count-1 ..

**Comment by t-edson** [comment]
How do I know, when "ed.LineBottom", change?

**Comment by t-edson** [comment]
I want to know a simple way to detect the scroll and the new Top and Bottom.

**Comment by Alexey-T** [comment]
-when "ed.LineBottom", change? 
In onchange, read LineBottom, see if changed...

-simple way to detect the scroll 
event OnScroll.

-and the new Top and Bottom.
no event OnFoldChanged- not yet.. U can see in OnCalcHilite if Top/Btm change

**Comment by t-edson** [comment]
A bug: When the editor is high less than a line, the cursor/selection doesn't work properly.

**Comment by t-edson** [comment]
What is the correect sequence of events, for one modification of the text?
I see these two cases:
1) OnEditorChange -> OnEditorCalcHilite
2) OnEditorCalcHilite -> OnEditorChange -> OnEditorCalcHilite

**Comment by Alexey-T** [comment]
I dunno: i need to test, pls test it?

**Comment by t-edson** [comment]
Those are the 2 cases I found, and it's no OK, to have sometimes OnEditorChange first and sometimes OnEditorCalcHilite  first.
You must have well defined the correct sequence of events for all the operations on the editor. It would make easier to implement the Adapter.

**Comment by t-edson** [comment]
There is need to test more, but the process for multiline tokens is done. The design optimize the use of memory, needing some aditional CPU. Reducing the value of LINES_PER_STATE, will reduce the CPU use, but increase the memory use.

**Comment by Alexey-T** [comment]
I ll see why Oncalchilite called first. maybe I find it. It makes a problem? No yet

> process for multiline tokens is done

it's good.

**Comment by t-edson** [comment]
I had to add a protection to avoid a crash, when OnEditorCalcHilite is called first. Anyway it would better to have an order on the events.

**Comment by t-edson** [comment]
I don't know if it's easy to include folding. How the folding is activated in ATSynEdit? Do you have a simple example?

**Comment by Alexey-T** [comment]
This adds 3 fold ranges

```
  Fold.Clear;

  //sorted by 2nd param
  Fold.Add(1, 4, 15, false, ''); //line 4 to 15
  Fold.Add(1, 5, 9, false, ''); //line 5 to 9
  Fold.Add(1, 7, 8, false, ''); //line 7 to 8
```

see param of Add

**Comment by Alexey-T** [comment]
>  states.Destroy;

never call Destroy: must call Free -it calls Desrtoy inside

**Comment by Alexey-T** [comment]
Added adapter proc OnEditorScroll //not tested

**Comment by t-edson** [comment]
What is "Fold"? Is it an object? Do I need to create? Is it predefined?
How does't it works? Can be overlapped?
Is the foldig, automatic updated when text is modified?
Can be defined without marks?

**Comment by t-edson** [comment]
I don't know what problem you have with "Destroy". I have never had problem with it. I know "Free" calls to "Destroy", and I know where I would need to use "Free".

**Comment by Alexey-T** [comment]
It's general mistake of new pascal coders. they call Destroy

**Comment by Alexey-T** [comment]
fold isnot updated if u modifi text. U need to upd it. See http://wiki.freepascal.org/ATSynEdit#Fold_object

**Comment by Alexey-T** [comment]
See http://wiki.freepascal.org/ATSynEdit#Fold_object
yes it's property Fold
Fold maybe partial updated if u modifi. i don't know details. My adapter updates Fold in each modifi

**Comment by t-edson** [comment]
> Added adapter proc OnEditorScroll //not tested

Adapter must have a event: Paint(), called before start to scan with OnEditorCalcHilite()

**Comment by Alexey-T** [comment]
maybe I'll add it.

**Comment by Alexey-T** [comment]
Adapter OnEditorPainttext done- called befr 1st OnCalcHilite

**Comment by Alexey-T** [comment]
Added- OnEditorBeforeCalcHilite(name like it)

**Comment by t-edson** [comment]
Good. I will try.

**Comment by Alexey-T** [comment]
It is working now? for all xml langs? (pascal.xml ...)

**Comment by t-edson** [comment]
I haven't tested in detail. Please, test if you can.
