### ISSUE TITLE
Bold etc

### ISSUE THREAD

**Issue by Alexey-T** [t-edson/SynFacilSyn#2]
Why keywords are bold. please make it option. i need to set "bold" or "italic" or "underline" for any token. better make key `style="bi"` so this is bold+italic or `style="u"` - this 's underline. for any token.

**Comment by t-edson** [comment]
OK, I will put the bold off for the Keywords on the next version. About the style, let me check if it's easy to include. I hope so.

**Comment by t-edson** [comment]
The tag "style" is implemented in version 0.9.1.
