### ISSUE TITLE
non ENG names

### ISSUE THREAD

**Issue by ghost** [t-edson/SynFacilSyn#22]
Very bad, you have non english names of vars. I cannot edit. Many books say--don't name var with non english. with russian. with spanish.
I cant find any var about 'block'

**Comment by t-edson** [comment]
Sorry I don't understand. Would you please be more specific?

**Comment by ghost** [comment]
I mean these are eng but very bad names-

```
txt   : string;       
orig  : string;       
TokPos: integer;      
tTok  : TSynHighlighte
typDel: TFaTypeDelim; 

dEnd  : string;       
pRange: TFaProcRange; 
folTok: boolean;      
chrEsc: char;         
//propiedades para man
bloIni : boolean;     
bloIniL: array of TFaS
bloFin : boolean;     
bloFinL: array of TFaS
secIni : boolean;     
secIniL: array of TFaS
firstSec: TFaSynBlock;
```

**Comment by t-edson** [comment]
Suggestions?
I don't pretend to have very good english Names. In fact, there is some spanish names. And even the name of the library "SynFacil" is basically Spanish.

**Comment by ghost** [comment]
TokenPos
TokenType
DelimeterPos
ProcRange
FollowingRange
BlockStart
BlockEnd
