### ISSUE TITLE
Update for last ATSynedit

### ISSUE THREAD

**Issue by Alexey-T** [t-edson/SynFacilSyn#25]
wish

- remove folder "atsynedit" (it is old version from 2018)
- add ATSynEdit_package to demo project require-list (IDE dialog Project Inspector)
- update sugnature of func

```
procedure TSynFacilAdapter.StringsLog(Sender: TObject; ALine: integer);
begin
  if (ALine>=0) and (ALine<firstModified) then firstModified := ALine;
//  DebugLn('OnLog: ALine=' + IntToStr(ALine) + ' ALen=' + IntToSTr(Alen));
end;
```

**Comment by t-edson** [comment]
OK. I will update.
WOuld you please explain better the part: "add ATSynEdit_package to demo project require-list (IDE dialog Project Inspector)"

**Comment by Alexey-T** [comment]
In IDE, open Project Inspector dialog when the demo ATSynEdit+SynFacil proj is opened.
You see list of files in project.
And requirement list. Add to this require-list - "atsynedit" package.
Or program cannot compile.

**Comment by t-edson** [comment]
No results for "atsynedit" package.  
![image](https://user-images.githubusercontent.com/7736802/57039913-928ed480-6c23-11e9-9755-ddb01667a483.png)

**Comment by Alexey-T** [comment]
it is here - first install this package in OnlinePackageManager.

**Comment by t-edson** [comment]
OK. Updated.
