### ISSUE TITLE
Error FSynEdit.Highlighter := loaded_highlighter

### ISSUE THREAD

**Issue by andr1972** [t-edson/SynFacilSyn#28]
I want use standard and SynFacilSyn highligters both due to XML special tags and Object Pascal nested comments. I have loaded c.xml from example to stringlist - langname + pointer to highlighter.
When I try
```
    FSynEdit.Lines.LoadFromFile(AFileName);
    FSynEdit.Highlighter := fHiSyntax.GetHighlighterByFileName(AFileName);
```
is error 

Is, ok ; was my error ; simply I searched DefaultFilter instrad of Ext

**Comment by t-edson** [comment]
I assume it's solved.
