### ISSUE TITLE
Attribute 'DIRECTIVE' doesnt exists

### ISSUE THREAD

**Issue by tigrazone** [t-edson/SynFacilSyn#34]
Hello.
Program fails with error when I run Sample_Project and open c_sample and select Syntax c.xml
Where is no 'DIRECTIVE' declaration
https://github.com/t-edson/SynFacilSyn/blob/2b5efc0047765fcac554b6d6c923ac8849574ee0/Sample_Project/c.xml#L6
How to fix it?

**Comment by t-edson** [comment]
Hi. 

I see is missing the DIRECTIVE token definition.
I've updated the c.xml file. Now it can be used without errors.

Greetings.

**Comment by tigrazone** [comment]
I check. Thank you for fixing
