### ISSUE TITLE
I need c lexer tips from you

### ISSUE THREAD

**Issue by tigrazone** [t-edson/SynFacilSyn#35]
Hello.
How to do c highlighter which:
1. processing string in #include "stdio.h" or #include <stdio.h> as string colored by string colors - i.e. between "" and <>?
2. how to work with #if #else #endif and try catch finally blocks for highlight these keywords and use these keywords for folding and highlight as block elements?

Thank you at all

**Comment by t-edson** [comment]
Hi.
You can define delimiter " for strings and every text between " and " will be highlighted.
You can define strings with "<" and ">" as delimiters too. However it will make every "<" char start a string and will fail in cases like "if (x<y) { }".
The easy way is to highlight all the line #include "stdio.h" or #include <stdio.h>, with something like:
```
  <Attribute Name="Directive" ForeCol="#FE2EF7"> </Attribute>
  <Token Start="#" End="" Attribute='DIRECTIVE'> </Token>
```
About #if #else #endif, you can define the folding using two sections inside a block:
```
  <Block Start="#if" End="#endif" Parent="Main">
    <Section Start="#if" FirstSec="True"> </Section>
    <Section Start="#else"> </Section>
  </Block>   
```
