### ISSUE TITLE
TsynFileSyn

### ISSUE THREAD

**Issue by Eudox67** [t-edson/SynFacilSyn#36]
Documentation mentions TSynFileSyn if you are not using code folding. Is that still available somewhere? I can't find it in the units. Maybe there used to be a SynFileSyn unit?

**Comment by t-edson** [comment]
Hi. There was a SynFileSyn highlighter I published a time ago. It was like a SynFacilSyn without code folding. I deleted it from my repository when I found some users got confused and used the wrong highlighter.

**Comment by Eudox67** [comment]
Ok. I have been learning how to use SynFacilSyn. Thank you!
