### ISSUE TITLE
Is Possible to have 2 character on start on token 

### ISSUE THREAD

**Issue by KikePie** [t-edson/SynFacilSyn#38]
Hi is possible to define the token start with 2 character instead of 1  i need define some highlither for thsi kind of commands but all them has 2 characters 
MD0,1MF,CF0,CF1,CF2,CF3,CF4,CF5,CF6,CF7,SE16382,UM1,SS2,PH0
MD1,VM,MN,SG100,SI100,SD1500,IL1000,SE16383,FA0,FV0,OO0
the MD0,MD1  is like a new line
 the CF IS CHANEL  
VM VELOCITY MOVE
MN MOTOR ON
YOU CAN SEE to start a command or instruction has 2 CHARACTERS BUT ALL HIGHLITHER HAS STAR TOKEN BUT IS ONLY 1 CHARACTER TO START I UNDERSTAND must instructions or tokens is like that any ides how i can implement that on tsynfacil or any other highligther...

any help welcome

thanks

**Comment by t-edson** [comment]
Hi. 

It depends on how do you want to highlight the line. You should give more details on that.
For example, tell if you want to have a specific color for the first word of the line and the same color for all the words. 
If you only have a limited words to highlights you can define a list.


Greetings

**Comment by KikePie** [comment]
Hi Edson thanks for replay i wanna to colored hole words only 3 can have a big list words MD(0-255) MJ(0-255) MC(0-255) the rest can be simple CF(0-7) not big deal to handle,..

I think to create a new class to change the start can be 2 or 3 characters...., and also i need just with 1 characters start is synfacil right now..


Thanks.

**Comment by t-edson** [comment]
Hi.

To highlight words starting with "MD" and followed by 0 or more numbers, just use:

`
  <Token Start="MD" Regex="[0-9]*" Attribute='STRING'> </Token>
`

**Comment by KikePie** [comment]
Thanks tito i made changes and tried to run but i don't  what i did wrong don't get works.
[mcdsyntax.zip](https://github.com/user-attachments/files/17803067/mcdsyntax.zip)
.

**Comment by t-edson** [comment]
Hi. The problem I see is that, as you're using tokens starting with "MD", "MJ", "MC" and "CF", you cannot use alphabetic characters as identifiers (at least not starting with "M" or "C"). So, your definition needs to redefine identifiers. 

First remove this:

```
   <Identifiers>
    <token attribute="Keyword">TK MF MN /token>  
   </Identifiers>
```

And Include this in your XML:

`  <Identifiers CharsStart= "@" Content = "A..Za..z0..9_"></Identifiers>`

This define identifiers as starting with "@" and won't be in conflict with your tokens starting with "M" or "C".

**Comment by KikePie** [comment]
Gracias Tito el fin de semana hice pruebas y lei la documentacion y finalmente vi que no es possible usar  synfacil para hacer esto, gracias por tu tiempo deja estudiaqr las possibles opnciones que tengo....
     On Thursday, November 21, 2024 at 07:11:19 AM PST, Tito Hinostroza ***@***.***> wrote:  
 
 


Hi. The problem I see is that, as you're using tokens starting with "MD", "MJ", "MC" and "CF", you cannot use alphabetic characters as identifiers (at least not starting with "M" or "C"). So, your definition needs to redefine identifiers.

First remove this:
   <Identifiers>
    <token attribute="Keyword">TK MF MN /token>  
   </Identifiers>

And Include this in your XML:

 <Identifiers CharsStart= "@" Content = "A..Za..z0..9_"></Identifiers>

This define identifiers as starting with "@" and won't be in conflict with your tokens starting with "M" or "C".
