### ISSUE TITLE
Longer func name

### ISSUE THREAD

**Issue by Alexey-T** [t-edson/SynFacilSyn#4]
Pls name longer, it's not ok now, not easy to guess what func does.

`procedure AddSymbSpecL` -> `AddSymbolSpecifierLight`
`procedure DefTokDelim` -> `GetDefaultTokenDelimeter`

**Comment by t-edson** [comment]
OK. It's going to change on the next version.

**Comment by t-edson** [comment]
On next version:

AddSymbSpecL() changed to  AddSymbSpecList() -> "Add Special Symbols from List"
AddIdentSpecL() changed to  AddIdentSpecList()-> "Add Special Identifier from List"

DefTokDelim  -> "Define Token Delimited". Could cause compatibility problems. I prefer maintain the name.

**Comment by Alexey-T** [comment]
ok, make some names longer.
