### ISSUE TITLE
Type name

### ISSUE THREAD

**Issue by Alexey-T** [t-edson/SynFacilSyn#6]
TFaNNNNNNN must be for all types, in Interface part. Code with same name may fail - in any unit which imports (uses) Synfacilsyn.

**Comment by t-edson** [comment]
I've changed just the types that can create conflict with other highlighters. Probably there is some others. I will check.

**Comment by Alexey-T** [comment]
see `interface` part - need "Fa" in ALL types (not only which conflict with other hiliters)
