### ISSUE TITLE
Incorrect colors in XML syntax

### ISSUE THREAD

**Issue by beNative** [t-edson/SynFacilSyn#9]
When I define eg. a new attribute like this:

`<Attribute Name="DIRECTIVE" ForeCol="Maroon" Style="b"/>`

the corresponding tokens will be purple. I haven't tested this for all colors but also Olive and Green seem to be incorrect. 

rgds,
Tim

**Comment by t-edson** [comment]
Probably I have a color translation error. I will check.

**Comment by t-edson** [comment]
Fixed. It will appear in the next version.
